// vgram.v generated by gen.v from the Telegram Bot API schema (Bot API 10.1.0).
// Do not edit by hand; re-run the generator (v run gen) instead.

module vgram

import net.http
import time
import json

// TelegramError is returned when the Bot API replies with `ok: false`. It
// implements IError, so it can be matched inside an `or { ... }` block:
//
//   msg := bot.send_message(chat_id: id, text: 'hi') or {
//       if err is vgram.TelegramError && err.retry_after > 0 {
//           // flood control: wait err.retry_after seconds and try again
//       }
//       return err
//   }
pub struct TelegramError {
pub:
	code               int    // Telegram error_code, e.g. 400, 401, 403, 409, 429
	description        string // human-readable description from Telegram
	migrate_to_chat_id i64    // set when a group has been migrated to a supergroup
	retry_after        i64    // seconds to wait before retrying (flood control, 429)
}

pub fn (e TelegramError) msg() string {
	return 'telegram: ${e.code} ${e.description}'
}

pub fn (e TelegramError) code() int {
	return e.code
}

// ApiResponse is the envelope wrapping every Bot API reply. ResponseParameters
// is a generated Bot API type (see types.v).
struct ApiResponse {
	ok          bool
	result      string @[raw]
	error_code  int
	description string
	parameters  ResponseParameters
}

pub struct Bot {
pub mut:
	token string
	// Base endpoint; the bot token and method name are appended. Override to
	// use a local Bot API server.
	endpoint string = 'https://api.telegram.org/bot'
	// Per-request read/write timeout. Set to 0 to wait indefinitely.
	timeout time.Duration = 30 * time.second
	// When true, outgoing requests and raw responses are logged to stderr.
	debug bool
	// Extra HTTP headers sent with every request (e.g. for a proxy).
	headers map[string]string
}

// new_bot creates a new Bot from a Telegram bot token.
pub fn new_bot(token string) Bot {
	return Bot{
		token: token
	}
}

// http_request performs a POST request against the Telegram Bot API and returns
// the raw JSON of the response `result` field. It returns a TelegramError when
// the API replies with `ok: false`, or the underlying transport error when the
// request itself fails. It is public so callers can invoke API methods that are
// not (yet) wrapped by a generated helper.
pub fn (b Bot) http_request(method string, data string) !string {
	mut header := http.new_header(key: .content_type, value: 'application/json')
	header.add_custom_map(b.headers)!
	mut req := http.Request{
		method:        .post
		url:           '${b.endpoint}${b.token}/${method}'
		data:          data
		header:        header
		read_timeout:  b.timeout
		write_timeout: b.timeout
	}
	if b.debug {
		eprintln('vgram request ${method}: ${data}')
	}
	resp := req.do()!
	if b.debug {
		eprintln('vgram response ${resp.status_code}: ${resp.body}')
	}
	api := json.decode(ApiResponse, resp.body) or {
		return error('vgram: invalid JSON in response to ${method}: ${err}')
	}
	if !api.ok {
		return TelegramError{
			code:               api.error_code
			description:        api.description
			migrate_to_chat_id: api.parameters.migrate_to_chat_id
			retry_after:        api.parameters.retry_after
		}
	}
	return api.result
}
