// vgram.v generated by gen.v from the Telegram Bot API schema (Bot API 10.1.0).
// Do not edit by hand; re-run the generator (v run gen) instead.

module vgram

import net.http
import os
import time
import json

// TelegramError is returned when the Bot API replies with `ok: false`. It
// implements IError, so it can be matched inside an `or { ... }` block:
//
//   msg := bot.send_message(chat_id: id, text: 'hi') or {
//       if err is vgram.TelegramError && err.retry_after > 0 {
//           // flood control: wait err.retry_after seconds and try again
//       }
//       return err
//   }
pub struct TelegramError {
pub:
	code               int    // Telegram error_code, e.g. 400, 401, 403, 409, 429
	description        string // human-readable description from Telegram
	migrate_to_chat_id i64    // set when a group has been migrated to a supergroup
	retry_after        i64    // seconds to wait before retrying (flood control, 429)
}

pub fn (e TelegramError) msg() string {
	return 'telegram: ${e.code} ${e.description}'
}

pub fn (e TelegramError) code() int {
	return e.code
}

// ApiResponse is the envelope wrapping every Bot API reply. ResponseParameters
// is a generated Bot API type (see types.v).
struct ApiResponse {
	ok          bool
	result      string @[raw]
	error_code  int
	description string
	parameters  ResponseParameters
}

pub struct Bot {
pub mut:
	token string
	// Base endpoint; the bot token and method name are appended. Override to
	// use a local Bot API server.
	endpoint string = 'https://api.telegram.org/bot'
	// Per-request read/write timeout. Set to 0 to wait indefinitely.
	timeout time.Duration = 30 * time.second
	// When true, outgoing requests and raw responses are logged to stderr.
	debug bool
	// Extra HTTP headers sent with every request (e.g. for a proxy).
	headers map[string]string
}

// new_bot creates a new Bot from a Telegram bot token.
pub fn new_bot(token string) Bot {
	return Bot{
		token: token
	}
}

fn (b Bot) method_url(method string) string {
	return '${b.endpoint}${b.token}/${method}'
}

// parse_response unwraps the Bot API envelope: it returns the raw JSON of the
// `result` field, a TelegramError when the API replies with `ok: false`, or a
// decode error for malformed JSON.
fn (b Bot) parse_response(resp http.Response, method string) !string {
	if b.debug {
		eprintln('vgram response ${resp.status_code}: ${resp.body}')
	}
	api := json.decode(ApiResponse, resp.body) or {
		return error('vgram: invalid JSON in response to ${method}: ${err}')
	}
	if !api.ok {
		return TelegramError{
			code:               api.error_code
			description:        api.description
			migrate_to_chat_id: api.parameters.migrate_to_chat_id
			retry_after:        api.parameters.retry_after
		}
	}
	return api.result
}

// http_request performs a JSON POST against the Telegram Bot API and returns the
// raw JSON of the response `result` field. It returns a TelegramError when the
// API replies with `ok: false`, or the underlying transport error when the
// request itself fails. It is public so callers can invoke API methods that are
// not (yet) wrapped by a generated helper.
pub fn (b Bot) http_request(method string, data string) !string {
	mut header := http.new_header(key: .content_type, value: 'application/json')
	header.add_custom_map(b.headers)!
	req := http.Request{
		method:        .post
		url:           b.method_url(method)
		data:          data
		header:        header
		read_timeout:  b.timeout
		write_timeout: b.timeout
	}
	if b.debug {
		eprintln('vgram request ${method}: ${data}')
	}
	resp := req.do()!
	return b.parse_response(resp, method)
}

// http_request_files performs a multipart/form-data POST, used to upload new
// files (photo, document, ...). `form` holds the textual parameters (chat_id,
// caption, the JSON of reply_markup, ...) and `files` maps each file field to
// its contents. Returns the raw JSON of the `result` field, like http_request.
//
//   photo := vgram.input_file_from_path('cat.jpg')!
//   raw := bot.http_request_files('sendPhoto', {'chat_id': id, 'caption': 'hi'},
//       {'photo': [photo]})!
//   msg := json.decode(vgram.Message, raw)!
pub fn (b Bot) http_request_files(method string, form map[string]string, files map[string][]http.FileData) !string {
	mut header := http.new_header()
	header.add_custom_map(b.headers)!
	if b.debug {
		eprintln('vgram request ${method}: multipart, ${form.len} field(s), ${files.len} file field(s)')
	}
	resp := http.post_multipart_form(b.method_url(method), http.PostMultipartFormConfig{
		form:   form
		files:  files
		header: header
	})!
	return b.parse_response(resp, method)
}

// input_file_from_path reads a local file into an http.FileData ready to be
// passed to http_request_files.
pub fn input_file_from_path(path string) !http.FileData {
	return http.FileData{
		filename:     os.file_name(path)
		content_type: content_type_for(path)
		data:         os.read_bytes(path)!.bytestr()
	}
}

fn content_type_for(path string) string {
	return match os.file_ext(path).to_lower() {
		'.jpg', '.jpeg' { 'image/jpeg' }
		'.png' { 'image/png' }
		'.gif' { 'image/gif' }
		'.webp' { 'image/webp' }
		'.mp4' { 'video/mp4' }
		'.mov' { 'video/quicktime' }
		'.mp3' { 'audio/mpeg' }
		'.ogg' { 'audio/ogg' }
		'.pdf' { 'application/pdf' }
		else { 'application/octet-stream' }
	}
}
